name: ${COMPOSE_NAME?COMPOSE_NAME must exist}

services:
  db:
    env_file: ${DB_ROOT?DB_ROOT must exist}/.env
    image: ${COMPOSE_NAME}-db
    container_name: ${COMPOSE_NAME}-db
    build:
      context: ${DB_ROOT}
      dockerfile: Containerfile
      args:
        WORKDIR: ${CONTAINERS_WORKDIR?CONTAINERS_WORKDIR must exist}/db
    expose:
      - 3306
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    depends_on:
      db:
        condition: service_started
    environment:
      PMA_USER: root
      PMA_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - ${PHP_MYADMIN_PORT}:80
    networks:
      - default

  app:
    depends_on:
      db:
        condition: service_started
    env_file: ${APP_ROOT?APP_ROOT must exist}/.env
    environment:
      DB_HOST: db
      APP_PORT: ${APP_PORT}
    image: ${COMPOSE_NAME}-app
    container_name: ${COMPOSE_NAME}-app
    build:
      context: ${APP_ROOT}
      dockerfile: Containerfile
      args:
        USER: ${APP_USER:?APP_USER must be non-empty}
    ports:
      - ${APP_PORT}:80
    networks:
      - default

networks:
  default:
    driver: bridge
