name: ${DOCKER_COMPOSE_NAME:?DOCKER_COMPOSE_NAME must be non-empty}

services:
  db:
    env_file: ${DB_ROOT?DB_ROOT must exist}/.env
    image: ${DOCKER_COMPOSE_NAME}/db
    container_name: ${DOCKER_COMPOSE_NAME}-db
    build:
      context: ${DB_ROOT}
      args:
        WORKDIR: ${DOCKER_WORKDIR?DOCKER_WORKDIR must exist}/db
    expose:
      - 3306
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    depends_on:
      - db
    environment:
      PMA_USER: root
      PMA_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - ${PHP_MYADMIN_PORT}:80
    networks:
      - default

  app:
    depends_on:
      - db
      - phpmyadmin
    env_file: ${APP_ROOT?APP_ROOT must exist}/.env
    environment:
      DB_HOST: db
      APP_PORT: ${APP_PORT}
    image: ${DOCKER_COMPOSE_NAME}/app
    container_name: ${DOCKER_COMPOSE_NAME}-app
    build:
      context: ${APP_ROOT}
      args:
        USER: ${DOCKER_USER:?DOCKER_USER must be non-empty}
    ports:
      - ${APP_PORT}:80
    networks:
      - default

networks:
  default:
    driver: bridge
